project:
  type: book

book:
  title: "mybook"
  author: "Jane Doe"
  date: "8/18/2021"
  chapters:
    - index.qmd
    - qmd/intro.qmd
    - qmd/summary.qmd


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
